services:
  ndk-213802_container:
    build:
      context: D:/PY_Code/Ceramic_Detection
      dockerfile: Dockerfile
    image: ndk-213802
    container_name: ndk-213802_container
    ports:
      - "55001:55001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - D:/PY_Code/Ceramic_Detection:/app
    networks:
      - ceramic-network
networks:
  ceramic-network:
    driver: bridge

#   laravel-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: ceramic-laravel
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - python-api
#     environment:
#       - APP_URL=http://localhost:8000
#       - DB_HOST=host.docker.internal
#       - DB_PORT=3306
#       - DB_DATABASE=ceramic
#       - DB_USERNAME=root
#       - DB_PASSWORD= # Để trống nếu XAMPP không đặt mật khẩu
#     networks:
#       - ceramic-network
#     healthcheck:
#       test: [ "CMD", "curl", "-f", "http://localhost" ]
#       interval: 30s
#       timeout: 10s
#       retries: 3

# networks:
#   ceramic-network:
#     driver: bridge
